name: Build and Push image to Dockerhub

env:
  DOCKERHUB_REPO: melashri/focalboard
  FOCALBOARD_MAJOR: 0
  FOCALBOARD_MINOR: 6
  FOCALBOARD_INCREMENT: 5

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker image labels
        uses: crazy-max/ghaction-docker-meta@v4.0.1
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          label-custom: |
            maintainer=melashri
            org.opencontainers.image.title=focalboard
            org.opencontainers.image.description=Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.
            org.opencontainers.image.url=https://www.focalboard.com
            org.opencontainers.image.version=${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          build-args: FOCALBOARD_REF=v${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}
            ${{ env.DOCKERHUB_REPO }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
